# rtmp推流配置，配置以后会优先采用

[kuaishou]
enable = true
rtmp_url = "rtmp://open-push.voip.yximgs.com/gifshow/xxxxx" # https://link.bilibili.com/p/center/index#/my-room/start-live 到这个地址申请
video_path = "/home/videos/" # 支持文件夹或单个文件
show_title = true
show_subtitle = false # 功能暂不可用

[bilibili]
enable = true
rtmp_url = "rtmp://open-push.voip.yximgs.com/gifshow/xxxxx" # https://studio.kuaishou.com/live/list
video_path = "/home/videos/" # 支持文件夹或单个文件
show_title = true
show_subtitle = false # 功能暂不可用
